# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20170911_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.IntegerField(default='99999999', null='True'),
        ),
    ]
