# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0002_instituicao_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
