# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0004_auto_20170907_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='image',
            field=models.ImageField(blank=b'True', null=b'True', upload_to=b'bandeiras'),
        ),
    ]
