# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('pj1c', models.CharField(max_length=2)),
                ('pj1f', models.CharField(max_length=2)),
                ('pj2c', models.CharField(max_length=2)),
                ('pj2f', models.CharField(max_length=2)),
                ('pj3c', models.CharField(max_length=2)),
                ('pj3f', models.CharField(max_length=2)),
                ('pj4c', models.CharField(max_length=2)),
                ('pj4f', models.CharField(max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
