# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palpite',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='palpite',
            name='published_date',
        ),
    ]
