# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0003_auto_20170818_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palpite',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
