# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0004_auto_20170823_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpite',
            name='total',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
