# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0005_palpite_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palpite',
            name='pj1c',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='pj1f',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='pj2c',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='pj2f',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='pj3c',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='pj3f',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='pj4c',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='pj4f',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='total',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
